# Generated by Django 5.1.3 on 2024-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_remove_song_genre_song_image_url_alter_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
